apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: osrm
  namespace: osrm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: osrm
  serviceName: osrm
  template:
    metadata:
      labels:
        app: osrm
    spec:
      containers:
        - image: iteam1337/osrm-sweden:latest
          name: osrm
          command: ["/bin/sh"]
          args:
            - -c
            - osrm-routed --algorithm mld --max-table-size 10000 /data/sweden-latest.osrm
          env:
            - name: DOWNLOAD_URL
              value: https://download.geofabrik.de/europe/sweden-latest.osm.pbf
          resources:
            requests:
              cpu: "0.3"
              memory: "512Mi"
          ports:
            - containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /nearest/v1/driving/21.033499654770427,64.74958466530941
              port: 5000
          readinessProbe:
            initialDelaySeconds: 100
            httpGet:
              path: /nearest/v1/driving/21.033499654770427,64.74958466530941
              port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: osrm
  namespace: osrm
  labels:
    app: osrm
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: osrm
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: osrm-ingress
  namespace: osrm
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - osrm.predictivemovement.se
      secretName: osrm-prod-tls
  rules:
    - host: osrm.predictivemovement.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: osrm
                port:
                  number: 5000