apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: otp
  namespace: otp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: otp
  serviceName: otp
  template:
    metadata:
      labels:
        app: otp
    spec:
      containers:
        - image: iteam1337/opentripplanner-sweden:latest
          name: otp
          resources:
            requests:
              cpu: "0.3"
              memory: "1024Mi"
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 300
            httpGet:
              path: otp/routers/default/plan?fromPlace=65.315849,21.474429&toPlace=65.583524,22.144603&mode=TRANSIT,WALK&maxWalkDistance=5000&arriveBy=false
              port: 8080
          readinessProbe:
            initialDelaySeconds: 100
            httpGet:
              path: otp/routers/default/plan?fromPlace=65.315849,21.474429&toPlace=65.583524,22.144603&mode=TRANSIT,WALK&maxWalkDistance=5000&arriveBy=false
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: otp
  namespace: otp
  labels:
    app: otp
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: otp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otp-ingress
  namespace: otp
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - otp.iteam.services
      secretName: otp-prod-tls
  rules:
    - host: otp.iteam.services
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: otp
                port:
                  number: 8080