name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v3

      - name: ğŸ”§ Build SampleAddresses
        uses: docker/build-push-action@v3
        with:
          context: packages/sampleAddresses

      - name: ğŸ”§ Build Simulator
        uses: docker/build-push-action@v3
        with:
          context: packages/simulator

      - name: ğŸ”§ Build Visualsation
        uses: docker/build-push-action@v3
        with:
          context: packages/visualisation
