name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:

  test-sample-addresses:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v3

      - name: ğŸ”§ Build SampleAddresses
        uses: docker/build-push-action@v4
        with:
          context: packages/sampleAddresses

  test-simulator:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v3

      - name: ğŸ”§ Build Simulator
        uses: docker/build-push-action@v4
        with:
          context: packages/simulator

  test-visualisation:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v3

      - name: ğŸ”§ Build Visualisation
        uses: docker/build-push-action@v4
        with:
          context: packages/visualisation
